version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: mysql:5.7 
    ports:
      - "3308:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "teste@123"
      MYSQL_DATABASE: laravel
      MYSQL_ALLOW_PUBLIC_KEY_RETRIEVAL: "true" 
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
